pipeline {
    agent {
			docker {
				image 'node:20'
			}
		}

    environment {
        CI = 'true'
    }

    parameters {
        booleanParam(name: 'FIX_LINT', defaultValue: false, description: 'Fix linting errors')
        booleanParam(name: 'SILENT_TEST', defaultValue: false, description: 'Run tests in silent mode')
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Prettier') {
            steps {
                sh 'npm run format'
            }
        }

        stage('Run ESLint') {
            steps {
                script {
                    if (params.FIX_LINT) {
                        sh 'npm run lint:fix'
                    } else {
                        sh 'npm run lint'
                    }
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    if (params.SILENT_TEST) {
                        sh 'npm run test:silent'
                    } else {
                        sh 'npm run test'
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'coverage/', allowEmptyArchive: true
        }
    }
}
